version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: new_system_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5433:5432"

  import_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/new_system_db
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test

  old:
    build:
      context: ./OldSystem
      dockerfile: Dockerfile
    ports:
      - "8081:8081"