
CREATE SCHEMA new_system_schema;
SET search_path TO new_system_schema;



CREATE TABLE new_system_schema.company_user (
                                            id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                            login varchar(255) NOT NULL,

                                            CONSTRAINT company_user_pkey PRIMARY KEY (id),
                                            CONSTRAINT company_user_uniq_login UNIQUE (login)
);

CREATE TABLE new_system_schema.patient_profile (
                                               id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                               first_name varchar(255) NULL,
                                               last_name varchar(255) NULL,
                                               old_client_guid varchar(255) NULL,
                                               status_id int2 NOT NULL,
                                               CONSTRAINT patient_profile_pkey PRIMARY KEY (id)
);


CREATE TABLE new_system_schema.patient_note (
                                            id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                            created_date_time timestamp NOT NULL,
                                            last_modified_date_time timestamp NOT NULL,
                                            created_by_user_id int8 NULL,
                                            last_modified_by_user_id int8 NULL,
                                            note varchar(4000) NULL,
                                            patient_id int8 NOT NULL,
                                            CONSTRAINT patient_note_pkey PRIMARY KEY (id)
);
ALTER TABLE new_system_schema.patient_note ADD CONSTRAINT fk_pat_note_to_modifyed_user FOREIGN KEY
    (last_modified_by_user_id) REFERENCES new_system_schema.company_user(id);
ALTER TABLE new_system_schema.patient_note ADD CONSTRAINT fk_pat_note_to_created_user FOREIGN KEY
    (created_by_user_id) REFERENCES new_system_schema.company_user(id);
ALTER TABLE new_system_schema.patient_note ADD CONSTRAINT fk_pat_note_to_patient FOREIGN KEY
    (patient_id) REFERENCES new_system_schema.patient_profile(id);


-- Вставка клиента со старыми guid содержащимися на old system
INSERT INTO new_system_schema.patient_profile (first_name, last_name, old_client_guid, status_id) VALUES
      ( '1', '1', '8e7e0ebb-0b5d-47c2-b716-d70fed1f7b1c,cd4a503d-e057-4571-ae8e-d0a93d34133a', '1');

-- Вставка user
insert into new_system_schema.company_user (login) values ('petya123');

-- Вставка заметки такой же как и в old system
INSERT INTO new_system_schema.patient_note (created_date_time, last_modified_date_time, created_by_user_id, last_modified_by_user_id, note, patient_id) VALUES
       ( '2012-12-12 12:12:12','2013-12-12 12:12:12','1', '1',  'like existed', '1');

-- Вставка заметки устарелой
INSERT INTO new_system_schema.patient_note (created_date_time, last_modified_date_time, created_by_user_id, last_modified_by_user_id, note, patient_id) VALUES
    ( '2015-12-12 12:12:12','2015-12-12 12:12:12','1', '1',  'expired entry', '1');

-- Вставка заметки более новой
INSERT INTO new_system_schema.patient_note (created_date_time, last_modified_date_time, created_by_user_id, last_modified_by_user_id, note, patient_id) VALUES
    ( '2009-12-12 12:12:12','2015-12-12 12:12:12','1', '1',  'not expired entry', '1');

-- Вставка клиента с заблок статусом
INSERT INTO new_system_schema.patient_profile (first_name, last_name, old_client_guid, status_id) VALUES
    ( '2', '2', 'f3a4ebcf-62e4-4d36-8a91-7639f5b8fa59', '200');


